# ─── Resource group ──────────────────────────────────────────────────────────

resource "azurerm_resource_group" "poc" {
  name     = var.resource_group_name
  location = var.location

  tags = {
    project     = "wss-unauthorized-client-poc"
    environment = "demo"
    cost_center = "security-research"
  }
}

# ─── SSH key pair (generated by Terraform, never leaves state) ───────────────

resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# ─── Random suffix for storage uniqueness ────────────────────────────────────

resource "random_id" "suffix" {
  byte_length = 4
}
